using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FEI.IRK.HM.RMR.Lib
{
    /// <summary>
    /// List with Path time items with all Robot trajectories 
    /// </summary>
    public class RobotPathTimeLine : List<RobotPathTimeItem>
    {

        /// <summary>
        /// Timeline data with specified trajectories for Localization Timeline
        /// </summary>
        /// <param name="TimelineData">Timeline Data generated by Timeline base class</param>
        public RobotPathTimeLine(TimelineItemList TimelineData)
        {
            double LastX = 0;
            double LastY = 0;
            TimelineItem[] ItemsWithSensorData = TimelineData.GetAllWithSensorData();
            for (int i = 0; i < TimelineData.Count; i++)
            {
                if (i > 0 && TimelineData[i].PositionX == LastX && TimelineData[i].PositionY == LastY)
                {
                    RobotPathTimeItem item = new RobotPathTimeItem();
                    item.FrameNo = i;
                    item.Paths = this.Last().Paths;
                    Add(item);
                }
                else
                {
                    TimelineItem LastPos = TimelineData[0];
                    int CountAccessed = ItemsWithSensorData.Count(TLItem => TLItem.FrameNo <= i && TLItem.SensorData != null);
                    List<RobotPath> Paths = new List<RobotPath>();
                    RobotPath Path = null;
                    for (int j = 0; j < CountAccessed; j++)
                    {
                        Path = new RobotPath();
                        Path.Position1 = LastPos;
                        Path.Position2 = ItemsWithSensorData[j];
                        Paths.Add(Path);
                        LastPos = ItemsWithSensorData[j];
                    }
                    Path = new RobotPath();
                    Path.Position1 = LastPos;
                    Path.Position2 = TimelineData[i];
                    Paths.Add(Path);
                    RobotPathTimeItem item = new RobotPathTimeItem();
                    item.FrameNo = i;
                    item.Paths = Paths.ToArray();
                    Add(item);
                }
            }
            GC.Collect();
        }
    }
}
